### ISSUE TITLE
Try to shorten the names of attributes

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#134] opened 2023-04-11 17:12 UTC
Related to [](url)https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/issues/69, the intent is to analuze the modules and try to shorten the names of attributes that appears too long, without loosing the meaning of the attribute.

**Comment by sergiobelotti** [comment] 2023-07-04 15:42
Looking at the tree it seems that the attributes more critical are:

- polarization-dispersion-penalty
- max-pol-dependent-loss-penalty

**Comment by EstherLerouzic** [comment] 2023-07-04 16:06
then we could use pmd-penalty and pdl-penalty

pmd and pdl are well known acronyms and description has the definition

**Comment by italobusi** [comment] 2023-07-05 09:54
> Looking at the tree it seems that the attributes more critical are:

Just one minor doubt: should it be pdl-penalty or max-pdl-penalty?

**Comment by sergiobelotti** [comment] 2023-07-05 13:27
Unfortunately to shorten same names of attributes does not solve the issue: Dieter showed me the .txt of version 13, with simulation importing the actual last tree related to PR#135 and there are 4 lines exceeding 72 line length all with the types field.
This is due to the 3 characters more added by the compilation from XML to txt . 
For example:
+--ro nominal-carrier-power?
                |           |  |          l0-types:power-in-dbm-or-null
editing the tree with normal editor we are still within 72 char, but txt process adding 3 more characters creating the issue.
Obviously we can partially mitigate the problem shortening some typedef names.

**Comment by italobusi** [comment] 2023-07-05 13:59
IMHO, for the two attributes mentioned above, the new names by proposed by Esther are better regardless of the line length issue

For the I-D submission, since there are only 4 lines, I would suggest to fix the issue manually and then to raise the issue with Netmod WG

One possibility could be to fold the YANG tree using the tool defined in RFC8792 but this option is currently precluded by the scope of RFC8792 based on the assumption that pyang can solve the line length issue which seems not correct based on our experience

**Comment by manzoro** [comment] 2023-11-20 08:58
As per our discussion on IETF-118 side meeting, I have analyzed the lines still with with >69 columns (by using rfcfold and double checking manually); the problem is mostly due to the tree indentation (as per Italo/Dieter observation on July 5) and cannot be fixed by just shortening the attribute name. The fix may require to shorten some definition in L0-types. 

For now I've not created yet a PR branch to work on it, I'm reporting here the affected lines that are all within the 'amplifier-element' section and highlighted in this comment, lets discuss together how to move forward in the next call.

```
                |           +--ro (power-param)?
                |           |  +--:(channel-power)
                |           |  |  +--ro nominal-carrier-power?
                |           |  |          l0-types:power-in-dbm-or-null            <-- exceed by 2 chars
                |           |  +--:(power-spectral-density)
                |           |     +--ro nominal-power-spectral-density?            <-- exceed by 2 chars
                |           |             l0-types:decimal-16-digits-or-null       <-- exceed by 7 chars
                |           +--ro raman-direction?
                |           |       enumeration
                |           +--ro raman-pump* []
                |           |  +--ro frequency?
                |           |  |       l0-types:frequency-thz
                |           |  +--ro power?
                |           |          l0-types:decimal-2-digits-or-null           <-- exceed by 3 chars
                |           +--ro pdl?
                |           |       l0-types:loss-in-db-or-null
                |           +--ro media-channel-groups
                |              +--ro media-channel-group* []
                |                 +--ro media-channels* []
                |                    +--ro flexi-n?
                |                    |       l0-types:flexi-n
                |                    +--ro flexi-m?
                |                    |       l0-types:flexi-m
                |                    +--ro delta-power?
                |                            l0-types:gain-in-db-or-null           <-- exceed by 3 chars
```

**Comment by sergiobelotti** [comment] 2023-11-20 12:12
@manzoro : thanks Roberto for the analysis. One question for clarification: when you say "The fix may require to shorten some definition in L0-types." you mean some typedef definitions or again to shorten some attributes name

**Comment by sergiobelotti** [comment] 2023-11-21 13:36
```
+--ro (power-param)?
                |           |  +--:(channel-power)
                |           |  |  +--ro nominal-carrier-power?
                |           |  |          l0-types:power-in-dbm-or-null            <-- exceed by 2 chars
dbm-or-null
                |           |  +--:(power-spectral-density)
                |           |     +--ro nominal-power-spectral-density?            <-- exceed by 2 chars
nom-power-spectral-density
                |           |             l0-types:decimal-16-digits-or-null       <-- exceed by 7 chars
psd-or-null
                |           +--ro raman-direction?
                |           |       enumeration
                |           +--ro raman-pump* []
                |           |  +--ro frequency?
                |           |  |       l0-types:frequency-thz
                |           |  +--ro power?
                |           |          l0-types:decimal-2-digits-or-null           <-- exceed by 3 chars
dec-2-digit-or-null
                |           +--ro pdl?
                |           |       l0-types:loss-in-db-or-null
                |           +--ro media-channel-groups
                |              +--ro media-channel-group* []
                |                 +--ro media-channels* []
                |                    +--ro flexi-n?
                |                    |       l0-types:flexi-n
                |                    +--ro flexi-m?
                |                    |       l0-types:flexi-m
                |                    +--ro delta-power?
                |                            l0-types:gain-in-db-or-null           <-- exceed by 3 chars
it is 
```

**Comment by sergiobelotti** [comment] 2023-11-21 14:50
Call on 11/21/23:
based on Roberto's analysis, we made some proposals to solve the various exceeded cases.

l0-types:power-in-dbm-or-null --> dbm-or-null
proposal: "dbm" is used just for power so no need to put power in the typedef.

nominal-power-spectral-density --> nom-power-spectral-density or, since "psd" can stand for power spectral density , an alterantive can be --> nominal-psd 

l0-types:decimal-16-digits-or-null --> we have already changed in l0-types into "power-spectral-desnsity-or-null" since decimal-16-digit-or-null is used only for power spectral density. So to shorten the type --> psd-or-null

l0-types:decimal-2-digits-or-null --> dec-2-digit-or-null

l0-types:gain-in-db-or-null --> have already been changed into ratio-in-db-or-null

We agreed do not change that since more clear "ratio-in-db-or-null"
Julien/Esther: we do not risk to loose clarity in the attempt to solve problem of indentation.

**Comment by egriseri** [comment] 2023-11-21 17:07
Hi @sergiobelotti I agree on the proposal. As additional comment I think nominal-psd is sleeker and easier to read than nom-power-spectral-density and more coherent with psd-or-null.

**Comment by sergiobelotti** [comment] 2023-11-22 14:20
> Hi @sergiobelotti I agree on the proposal. As additional comment I think nominal-psd is sleeker and easier to read than nom-power-spectral-density and more coherent with psd-or-null.

@egriseri Thanks Enrico, I agree on you preference about nominal-psd

**Comment by italobusi** [comment] 2023-11-22 22:59
> SB> **power-dbm** would be ok for me. For power-watt I'm wondering if it is the case to define a type for a single attribute (power in the pump) , that is defined as decimal-2-digits-or-null, type that is used in other attributes that are nothing to do with power.
> 

IB> Not a strong opinion from me. I was just thinking about a possible comment asking why `power-dbm` and not just `power` as in other cases

> @italobusi : do you think can we have BC issues with these changes with respect modules importing the old RFC9093 ?

IB: I think so because, if I recall well, we are changing definitions which were not in RFC9093. However, it is worthwhile checking that all the changes we are doing are BC with RFC9093. I have created issue #161 not to forget: I do not know which label to assign to it to indicate that this is something to do before WG LC

**Comment by sergiobelotti** [comment] 2023-11-23 09:22
> > SB> **power-dbm** would be ok for me. For power-watt I'm wondering if it is the case to define a type for a single attribute (power in the pump) , that is defined as decimal-2-digits-or-null, type that is used in other attributes that are nothing to do with power.
> 
> IB> Not a strong opinion from me. I was just thinking about a possible comment asking why `power-dbm` and not just `power` as in other cases
> 
> > @italobusi : do you think can we have BC issues with these changes with respect modules importing the old RFC9093 ?
> 
> IB: I think so because, if I recall well, we are changing definitions which were not in RFC9093. However, it is worthwhile checking that all the changes we are doing are BC with RFC9093. I have created issue #161 not to forget: I do not know which label to assign to it to indicate that this is something to do before WG LC

What about "before-WG LC"  as label ?

**Comment by ju7ien** [comment] 2023-11-23 09:26
> > SB> **power-dbm** would be ok for me. For power-watt I'm wondering if it is the case to define a type for a single attribute (power in the pump) , that is defined as decimal-2-digits-or-null, type that is used in other attributes that are nothing to do with power.
> 
> IB> Not a strong opinion from me. I was just thinking about a possible comment asking why `power-dbm` and not just `power` as in other cases

I think there's no value in creating a new unit type for power-watt and decimal-2-digits-or-null is perfectly fine.

**Comment by manzoro** [comment] 2023-11-24 09:51
@italobusi  and @sergiobelotti:  I've seen the commits applied in wg-lc-prep as per the discussion here, I have one more proposal to remove one additional long line: we replaced power-spectral-density with psd in the attributes names, why don't do it also in the L0types for consistency so that we get change of
```
                |           |     +--:(power-spectral-density)
                |           |        +--ro nominal-psd
                |           |                l0-types:power-spectral-density-or-null
```
into
```
                |           |     +--:(power-spectral-density)
                |           |        +--ro nominal-psd
                |           |                l0-types:psd-or-null
```

**Closed as completed** 2024-01-23 14:39 UTC
Labels: YANG model update
